### ISSUE TITLE
error regarding web3j and related APIs

### ISSUE THREAD

**Issue by AlexFalzone** [YanchWare/internship-dpki#8]
@amenuor <br><br>First of all, the problem is the lack of documentation on how to use the APIs. <br> Secondly, it is impossible to build any java file, because web3j imports are reported as errors. <br> 

![immagine](https://user-images.githubusercontent.com/89725713/186701852-fa1d8cc8-4377-4f7e-a582-b0b2fc93c144.png)            <br>  Below is a mini guide on how to install web3j etc... <br><br> - To install web3j:  `curl -L get.web3j.io | sh && source ~/.web3j/source.sh
` <br> After that it is possible to create, and import a project with the related APIs (for the import it is necessary to include the path of the smart contract). It is possible to create only the APIs with `$ web3j openapi generate \
    --solidity-path <path_to_Solidity_contracts> \
    --with-implementations=true
` <br> <br> Subsequently a folder will be created, inside there are various files, the one we are interested in will be under the name of dpki.sol <br>

**Comment by amenuor** [comment]
Hello Alex!
Thank you for creating an issue on this, I think it is a great idea to share knowledge in a way that is going to be persistent.
The first thing you need to do before starting any project in any programming language is to know what kind of program you want to create.

Once that is clear, you need to set up your project for the chosen programming language.

In our case, we need to create a console program for a PoC in Java.

There are different ways to set up a Java project, (Ant, Gradle, Maven) and we will proceed with Maven, as this is what we usually use here at YanchWare.

I would advise you to read about Maven [here](https://maven.apache.org/guides/getting-started/). I have done those steps for you and I have committed now to your branch.

When looking for dependencies, you can use https://search.maven.org/ (a.k.a. maven central) and add them to your `pom.xml` file in order to instruct maven to get the required jar files from its pubic repos.

Finally you can build, test and package with `mvn package`

To understand that command, please read about the Lifecycle [here](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)

**Comment by amenuor** [comment]
Ok this is for the basics.
Now that we have a nice Maven project, you need to find the documentation.
I can see quite some docs on this here:

- https://github.com/web3j/web3j
- https://docs.web3j.io/4.8.7/

Specifically for maven: https://github.com/web3j/web3j-maven-plugin

**Comment by amenuor** [comment]
Now you should have a project working. You should run `npm install` in the `/src/main/resource` folder.
Then, in the main folder of the project (where the `pom.xml` file is located) you can run `mvn web3j:generate-sources`

It could be nice to automate some of these steps later on.

**Comment by AlexFalzone** [comment]
Resolved
